services:
  - type: web
    name: bakery-app
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn bakery.wsgi:application
    autoDeploy: true
    envVars:
      - key: DJANGO_SECRET_KEY
        sync: false
      - key: DEBUG
        value: 'False'
      - key: ALLOWED_HOSTS
        value: bakery-app.onrender.com
      - key: DATABASE_URL
        sync: false
